final_cost_trip = [
    {
        "provider": "zeus",
        "city": "tubingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": 0,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "schwabisch_gmund",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "goppingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "pforzheim",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "renningen_malmsheim",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "heidelberg",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "konstanz",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "ludwigsburg",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "freiburg",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "zeus",
        "city": "villingen_schwenningen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "uberingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "lindau",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "basel",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "tubingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "winterthur",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "reutlingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "boblingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "bregenz",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "ludwigsburg",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "heidelberg",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "kaiserslautern",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "friedrichshafen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "karlsruhe",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "st gallen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "zurich",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "mannheim",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "mainz",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "ulm",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "heilbronn",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "stuttgart",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "dott",
        "city": "saarbrucken",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "bolt",
        "city": "zurich",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "bolt",
        "city": "basel",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "bolt",
        "city": "stuttgart",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "bolt",
        "city": "reutlingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "bolt",
        "city": "karlsruhe",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_ch",
        "city": "zurich",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_ch",
        "city": "basel",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_de",
        "city": "tubingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_de",
        "city": "kalrsruhe",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_de",
        "city": "mannheim",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_de",
        "city": "pforzheim",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_de",
        "city": "reutlingen",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
    {
        "provider": "voi_de",
        "city": "stuttgart",
        "vehicle_id": None,
        "km_trip": None,
        "soc_start": None,
        "soc_end": None,
        "delta_soc": None,
        "battery_voltage": 36,
        "battery_capacity": 11,
        "soc_min": 0.15,
        "soc_max": 0.9,
        "e_batt": 396,
        "e_trip_i": None,
        "e_usable": 297,
        "p_elec": 0.01,
        "eta_chg": 0.85,
        "cost_elec_i": 0,
        "c_batt": 450,
        "l_batt_km": 11000,
        "cost_wear_i": None,
        "r_lab": 12,
        "t_swap": 0.33,
        "cost_lab_i": 0,
        "cost_i": 0,
    },
]


final_revenue = [
    {
        "provider": "zeus",
        "city": "tubingen",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "schwabisch_gmund",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "goppingen",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "pforzheim",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "renningen_malmsheim",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "heidelberg",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "konstanz",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "ludwigsburg",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "freiburg",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "zeus",
        "city": "villingen_schwenningen",
        "unlock_fee": 0.5,
        "price_per_ride_pm": 0.25,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "uberingen",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.38,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "lindau",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.35,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "basel",
        "unlock_fee": 1.61,
        "price_per_ride_pm": 0.48,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "tubingen",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.27,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "winterthur",
        "unlock_fee": 1.08,
        "price_per_ride_pm": 0.53,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "reutlingen",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.27,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "boblingen",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.29,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "bregenz",
        "unlock_fee": 1.2,
        "price_per_ride_pm": 0.35,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "ludwigsburg",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.38,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "heidelberg",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.29,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "kaiserslautern",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.35,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "friedrichshafen",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.36,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "karlsruhe",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.29,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "st gallen",
        "unlock_fee": 1.29,
        "price_per_ride_pm": 0.48,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "zurich",
        "unlock_fee": 1.61,
        "price_per_ride_pm": 0.48,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "mannheim",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.29,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "mainz",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.29,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "ulm",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.38,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "heilbronn",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.27,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "stuttgart",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.27,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "dott",
        "city": "saarbrucken",
        "unlock_fee": 1,
        "price_per_ride_pm": 0.38,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "bolt",
        "city": "zurich",
        "unlock_fee": 0.85,
        "price_per_ride_pm": 0.52,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "bolt",
        "city": "basel",
        "unlock_fee": 0.54,
        "price_per_ride_pm": 0.53,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "bolt",
        "city": "stuttgart",
        "unlock_fee": 0.47,
        "price_per_ride_pm": 0.19,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "bolt",
        "city": "reutlingen",
        "unlock_fee": 0,
        "price_per_ride_pm": 0.2,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "bolt",
        "city": "karlsruhe",
        "unlock_fee": 0.89,
        "price_per_ride_pm": 0.22,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_ch",
        "city": "zurich",
        "unlock_fee": 1.07,
        "price_per_ride_pm": 0.43,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_ch",
        "city": "basel",
        "unlock_fee": 1.07,
        "price_per_ride_pm": 0.47,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_de",
        "city": "tubingen",
        "unlock_fee": 0,
        "price_per_ride_pm": 0.22,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_de",
        "city": "kalrsruhe",
        "unlock_fee": 0.99,
        "price_per_ride_pm": 0.22,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_de",
        "city": "mannheim",
        "unlock_fee": 0.49,
        "price_per_ride_pm": 0.22,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_de",
        "city": "pforzheim",
        "unlock_fee": 0.49,
        "price_per_ride_pm": 0.22,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_de",
        "city": "reutlingen",
        "unlock_fee": 0.49,
        "price_per_ride_pm": 0.22,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "voi_de",
        "city": "stuttgart",
        "unlock_fee": 0.99,
        "price_per_ride_pm": 0.21,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "lime",
        "city": "stuttgart",
        "unlock_fee": 1.00,
        "price_per_ride_pm": 0.29,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "lime",
        "city": "zurich",
        "unlock_fee": 1.50,
        "price_per_ride_pm": 0.50,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
    {
        "provider": "lime",
        "city": "opfikon",
        "unlock_fee": 1.50,
        "price_per_ride_pm": 0.50,
        "vehicle_id": None,
        "trip_duration_min": None,
        "revenue_per_km": None,
    },
]
